In [ ]:
# Demonstrate three different methods for creating identical 2D arrays in NumPy. Provide the code for each 
#method and the final output after each method

In [ ]:
#1. Using numpy.array

In [11]:
import numpy as np

array1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#2.using np.arange and np.shape

In [20]:
array2=np.arange(1,10).reshape(3,3)
print(array2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [23]:
#3.using numpy.fromfunction

In [24]:
array3=np.fromfunction(lambda i,j : 1+i * 3+j ,(3,3) , dtype=int)
print(array3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#2. Using the Numpy function, generate an array of 100 evenly spaced numbers between 1 and 10 and 
#Reshape that 1D array into a 2D array

In [32]:
array_line=np.linspace(1,10,100,)
print(array_line)

#reshaping 1D array to 2D array
array_2d=array_line.reshape((10,10))
print(array_2d)

[ 1.          1.09090909  1.18181818  1.27272727  1.36363636  1.45454545
  1.54545455  1.63636364  1.72727273  1.81818182  1.90909091  2.
  2.09090909  2.18181818  2.27272727  2.36363636  2.45454545  2.54545455
  2.63636364  2.72727273  2.81818182  2.90909091  3.          3.09090909
  3.18181818  3.27272727  3.36363636  3.45454545  3.54545455  3.63636364
  3.72727273  3.81818182  3.90909091  4.          4.09090909  4.18181818
  4.27272727  4.36363636  4.45454545  4.54545455  4.63636364  4.72727273
  4.81818182  4.90909091  5.          5.09090909  5.18181818  5.27272727
  5.36363636  5.45454545  5.54545455  5.63636364  5.72727273  5.81818182
  5.90909091  6.          6.09090909  6.18181818  6.27272727  6.36363636
  6.45454545  6.54545455  6.63636364  6.72727273  6.81818182  6.90909091
  7.          7.09090909  7.18181818  7.27272727  7.36363636  7.45454545
  7.54545455  7.63636364  7.72727273  7.81818182  7.90909091  8.
  8.09090909  8.18181818  8.27272727  8.36363636  8.45454545  8.545

In [ ]:
# Explain the following terms
 #The difference in np.array, np.asarray and np.asanyarray
 #The difference between Deep copy and shallow copy

In [33]:
#np.array 

#np.array is a function used to create a new NumPy array from any object exposing the array interface, such as lists, tuples, or other arrays.
#It always returns a new array, unless the input is already a NumPy array with the specified dtype.
#Creates a new array
#Copies data by default
#Can change data type



In [ ]:
#np.asarray

#np.asarray is similar to np.array, but with an important difference: it does not make a copy if the input is already a NumPy array 
#of the correct dtype. 
#This function is used to convert input to an array, but it avoids unnecessary data copying when possible.


#Avoids copying
#Cannot change data type

In [ ]:
#np.asanyarray
#np.asanyarray is similar to np.asarray, but it passes through subclasses of ndarray. 
#This means that if the input is a subclass of ndarray (such as a masked array or matrix), it will return the input as is, preserving the subclass.

#Preserves subclasses
#Avoids copying


In [ ]:
 #The difference between Deep copy and shallow copy
    
#Shallow Copy
#A shallow copy creates a new object, but inserts references into it to the objects found in the original. 
#This means that the copy is only one level deep and modifications to objects inside the copied structure will reflect in the original, 
#since they reference the same objects.    
    
#Deep Copy
#A deep copy creates a new object and recursively copies all objects found in the original, effectively duplicating the entire structure. 
#This means that the new object and the original object are completely independent of each other.    
    

In [ ]:
#4. Generate a 3x3 array with random floating-point numbers between 5 and 20. Then, round each number in 
#the array to 2 decimal places

In [10]:
import numpy as np
ran_array=np.random.uniform(5,20,(3,3))
print(ran_array)



[[12.6052448  10.5202172   5.79126483]
 [16.68254505 15.00731994 15.20698047]
 [14.1175734   9.12157733 17.93311791]]


In [11]:
#rounding to 2 decimal points

roun_array=np.round(ran_array,2)
print(roun_array)


[[12.61 10.52  5.79]
 [16.68 15.01 15.21]
 [14.12  9.12 17.93]]


In [ ]:
'''5.Create a NumPy array with random integers between 1 and 10 of shape (5, 6). After creating the array 
perform the following operations:

 a)Extract all even integers from array.
 b)Extract all odd integers from array'''

In [14]:
#creating random number b/w 1 and 10
rand_array=np.random.randint(1,11,(5,6))
print(rand_array)

[[ 2  3  2  9  3 10]
 [ 5  8  2  5  9 10]
 [ 3  9  8  4  7  1]
 [ 4  6  7  1  2 10]
 [ 9  4  3  6  5  6]]


In [15]:
#a)Extract all even integers from array.

even_rand=rand_array[rand_array %2==0]
print(even_rand)

[ 2  2 10  8  2 10  8  4  4  6  2 10  4  6  6]


In [16]:
# b)Extract all odd integers from array

odd_rand=rand_array[rand_array %2!=0]
print(odd_rand)

[3 9 3 5 5 9 3 9 7 1 7 1 9 3 5]


In [ ]:
'''6.Create a 3D NumPy array of shape (3, 3, 3) containing random integers between 1 and 10. Perform the 
following operations:

 a) Find the indices of the maximum values along each depth level (third axis).
 b) Perform element-wise multiplication of between both array'''

In [17]:
#3D NumPy array of shape (3, 3, 3) containing random integers between 1 and 10
array_3=np.random.randint(1,11,(3,3,3))
print(array_3)

[[[ 4 10  3]
  [ 7  5  4]
  [ 1 10 10]]

 [[ 1  3  1]
  [ 3 10  7]
  [ 5  7  1]]

 [[ 8  2  2]
  [10  7  8]
  [ 5  5  7]]]


In [18]:
#a) Find the indices of the maximum values along each depth level (third axis).

max_array=np.argmax(array_3,axis=2)
print(max_array)


[[1 0 1]
 [1 1 1]
 [0 0 2]]


In [19]:
#b) Perform element-wise multiplication of between both array

ele_mul=array_3*array_3
print(ele_mul)


[[[ 16 100   9]
  [ 49  25  16]
  [  1 100 100]]

 [[  1   9   1]
  [  9 100  49]
  [ 25  49   1]]

 [[ 64   4   4]
  [100  49  64]
  [ 25  25  49]]]
